<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>OllamaToolkit.App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OllamaToolkit.Core\OllamaToolkit.Core.csproj" />
    <ProjectReference Include="..\OllamaToolkit.BenchmarkStore\OllamaToolkit.BenchmarkStore.csproj" />
    <ProjectReference Include="..\OllamaToolkit.BenchmarkRunner\OllamaToolkit.BenchmarkRunner.csproj" />
    <ProjectReference Include="..\OllamaToolkit.AiAssist\OllamaToolkit.AiAssist.csproj" />
    <ProjectReference Include="..\OllamaToolkit.ModelRegistry\OllamaToolkit.ModelRegistry.csproj" />
    <ProjectReference Include="..\OllamaToolkit.ModelCatalog\OllamaToolkit.ModelCatalog.csproj" />
    <ProjectReference Include="..\OllamaToolkit.ModelCategory\OllamaToolkit.ModelCategory.csproj" />
  </ItemGroup>

</Project>